<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-13T00:57:38 IST" name="Default suite" finished-at="2021-06-13T00:58:08 IST" duration-ms="30356">
    <groups>
    </groups>
    <test started-at="2021-06-13T00:57:38 IST" name="Default test" finished-at="2021-06-13T00:58:08 IST" duration-ms="30356">
      <class name="com.wipro.scripts.TS04Test">
        <test-method is-config="true" signature="generateReport()[pri:0, instance:com.wipro.scripts.TS04Test@503d687a]" started-at="2021-06-13T00:57:38 IST" name="generateReport" finished-at="2021-06-13T00:57:38 IST" duration-ms="516" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateReport -->
        <test-method is-config="true" signature="invokeDriver()[pri:0, instance:com.wipro.scripts.TS04Test@503d687a]" started-at="2021-06-13T00:57:38 IST" name="invokeDriver" finished-at="2021-06-13T00:57:46 IST" duration-ms="7182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invokeDriver -->
        <test-method is-config="true" signature="methodName(java.lang.reflect.Method)[pri:0, instance:com.wipro.scripts.TS04Test@503d687a]" started-at="2021-06-13T00:57:46 IST" name="methodName" finished-at="2021-06-13T00:57:46 IST" duration-ms="28" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.wipro.scripts.TS04Test.add_Address_and_remove_address() throws com.codoid.products.exception.FilloException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodName -->
        <test-method signature="add_Address_and_remove_address()[pri:0, instance:com.wipro.scripts.TS04Test@503d687a]" started-at="2021-06-13T00:57:46 IST" name="add_Address_and_remove_address" finished-at="2021-06-13T00:58:07 IST" duration-ms="20982" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Address deleted] but found [Address saved]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Address deleted] but found [Address saved]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.wipro.reuse.Commonfunction.removeAddress(Commonfunction.java:113)
at com.wipro.scripts.TS04Test.add_Address_and_remove_address(TS04Test.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add_Address_and_remove_address -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:com.wipro.scripts.TS04Test@503d687a]" started-at="2021-06-13T00:58:07 IST" name="afterClass" finished-at="2021-06-13T00:58:08 IST" duration-ms="1550" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.wipro.scripts.TS04Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
